version: '3.8'

services:
  logoarr:
    image: swguru2004/logoarr:latest
    container_name: logoarr
    ports:
      - "5000:5000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - /path/to/movies:/movies
      - /path/to/kids-movies:/kids-movies
      - /path/to/movies2:/movies2
      - /path/to/kids-movies2:/kids-movies2
      - /path/to/tv:/tv
      - /path/to/kids-tv:/kids-tv
      - /path/to/tv2:/tv2
      - /path/to/kids-tv2:/kids-tv2
    restart: unless-stopped
